version: 0.2

phases:
  install:
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - dist/**/*
    - package.json
  name: BuildArtifact
  base-directory: backend
