AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ticket Track Backend Lambda Functions

Parameters:
  MongoDbUri:
    Type: String
    Description: MongoDB connection URI

Resources:
  ScrapeEventUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/ticket/scrapeEventUrls.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/scrapeEventUrls
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        ScrapeEventUrlsApi:
          Type: Api
          Properties:
            Path: /ticket/scrapeEventUrls
            Method: POST

  ScrapeTicketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/ticket/scrapeTickets.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/scrapeTickets
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        ScrapeTicketsApi:
          Type: Api
          Properties:
            Path: /ticket/scrapeTickets
            Method: POST

  FetchTicketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/ticket/fetchTickets.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/fetchTickets
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        FetchTicketsApi:
          Type: Api
          Properties:
            Path: /ticket/fetchTickets
            Method: GET
  
  AddHomeGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/game/addHomeGames.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/addHomeGames
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        AddHomeGamesApi:
          Type: Api
          Properties:
            Path: /game/addHomeGames
            Method: POST
  
  AddTicketAppUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/game/addTicketAppUrl.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/addTicketAppUrl
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        AddTicketAppUrlApi:
          Type: Api
          Properties:
            Path: /game/addTicketAppUrl
            Method: POST
  
  RefreshTicketsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/game/refreshTickets.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/refreshTickets
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        RefreshTicketsApi:
          Type: Api
          Properties:
            Path: /game/refreshTickets
            Method: POST
  
  FetchGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/game/fetchGames.handler
      Runtime: nodejs22.x
      CodeUri: ./dist/fetchGames
      Timeout: 20
      Environment:
        Variables:
          MONGODB_URI: !Ref MongoDbUri
      Events:
        FetchGamesApi:
          Type: Api
          Properties:
            Path: /game/fetchGames
            Method: GET
